import { Profile } from "./types";

export const DEMO_PROFILES: Profile[] = [
  {
    id: "demo-1",
    name: "Jordan Rivera",
    linkedinUrl: "https://linkedin.com/in/jordanrivera",
    currentTitle: "Head of Product",
    currentCompany: "Stripe",
    headline: "Building the future of payments | Ex-Meta, Ex-Uber",
    avatarInitials: "JR",
    addedAt: "2025-12-01T08:00:00Z",
    lastChecked: "2026-02-19T09:30:00Z",
    changes: [
      {
        id: "c1",
        timestamp: "2026-02-14T10:00:00Z",
        field: "title",
        oldValue: "Senior PM",
        newValue: "Head of Product",
      },
      {
        id: "c2",
        timestamp: "2026-02-14T10:00:00Z",
        field: "headline",
        oldValue: "Product @ Stripe | Ex-Meta, Ex-Uber",
        newValue: "Building the future of payments | Ex-Meta, Ex-Uber",
      },
      {
        id: "c3",
        timestamp: "2026-01-03T14:00:00Z",
        field: "company",
        oldValue: "Meta",
        newValue: "Stripe",
      },
      {
        id: "c4",
        timestamp: "2026-01-03T14:00:00Z",
        field: "title",
        oldValue: "Product Lead, Instagram",
        newValue: "Senior PM",
      },
    ],
  },
  {
    id: "demo-2",
    name: "Alex Chen",
    linkedinUrl: "https://linkedin.com/in/alexchen",
    currentTitle: "Funemployed",
    currentCompany: "Open to Work",
    headline: "Taking a break. Previously built things at Google.",
    avatarInitials: "AC",
    addedAt: "2025-11-15T08:00:00Z",
    lastChecked: "2026-02-19T09:30:00Z",
    changes: [
      {
        id: "c5",
        timestamp: "2026-02-10T16:00:00Z",
        field: "headline",
        oldValue: "Staff Engineer @ Google | Systems & Infrastructure",
        newValue: "Taking a break. Previously built things at Google.",
      },
      {
        id: "c6",
        timestamp: "2026-02-10T16:00:00Z",
        field: "title",
        oldValue: "Staff Software Engineer",
        newValue: "Funemployed",
      },
      {
        id: "c7",
        timestamp: "2026-02-10T16:00:00Z",
        field: "company",
        oldValue: "Google",
        newValue: "Open to Work",
      },
    ],
  },
  {
    id: "demo-3",
    name: "Sam Nakamura",
    linkedinUrl: "https://linkedin.com/in/samnakamura",
    currentTitle: "Co-Founder & CEO",
    currentCompany: "Stealth Startup",
    headline: "Building something new in AI. YC S25.",
    avatarInitials: "SN",
    addedAt: "2025-10-20T08:00:00Z",
    lastChecked: "2026-02-19T09:30:00Z",
    changes: [
      {
        id: "c8",
        timestamp: "2026-01-20T12:00:00Z",
        field: "company",
        oldValue: "Anthropic",
        newValue: "Stealth Startup",
      },
      {
        id: "c9",
        timestamp: "2026-01-20T12:00:00Z",
        field: "title",
        oldValue: "Research Engineer",
        newValue: "Co-Founder & CEO",
      },
      {
        id: "c10",
        timestamp: "2026-01-20T12:00:00Z",
        field: "headline",
        oldValue: "AI Safety Research @ Anthropic",
        newValue: "Building something new in AI. YC S25.",
      },
    ],
  },
  {
    id: "demo-4",
    name: "Taylor Brooks",
    linkedinUrl: "https://linkedin.com/in/taylorbrooks",
    currentTitle: "VP of Engineering",
    currentCompany: "Databricks",
    headline: "VP Eng @ Databricks | Scaling data infrastructure",
    avatarInitials: "TB",
    addedAt: "2025-09-01T08:00:00Z",
    lastChecked: "2026-02-19T09:30:00Z",
    changes: [],
  },
];
